# Generated by Django 6.0.6 on 2026-06-25 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_organizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.CharField(max_length=255)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('ticket_type', models.CharField(choices=[('general', 'General Admission'), ('vip', 'VIP'), ('student', 'Student'), ('early_bird', 'Early Bird'), ('group', 'Group'), ('other', 'Other')], default='general', max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='event.event')),
            ],
            options={
                'ordering': ['-registration_date'],
            },
        ),
        migrations.DeleteModel(
            name='Attendee',
        ),
    ]
